apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:    
      containers:
      - name: blue
        image: ankushsatpute/ltidockerdemo:tagVersion
        imagePullPolicy: Always      
        ports:
        - containerPort: 8080
